### ISSUE TITLE
Running with `--dev`, all urls seem to redirect back to the root url

### ISSUE THREAD

**Issue by gridbugs** [ocaml-dune/binary-distribution#102] opened 2024-10-18 07:57 UTC
The site works as expected when running without --dev, but with --dev I keep getting redirected back to root. It seems to be related to the live releading as if I remove that it works as expected, even when I pass --dev.

**Comment by maiste** [comment] 2024-10-21 13:18
The live reload acts like a `F11` and reload the website when something changes. Do you have more context about what happens, I’m not sure to understand exactly the issue :sweat_smile:

**Comment by gridbugs** [comment] 2024-10-22 02:15
I ran into this while trying out the new 404 page. I went to http://0.0.0.0:8080/foo and it just took me back to http://0.0.0.0:8080/.

**Comment by maiste** [comment] 2024-10-22 10:02
```js
var socketUrl = "ws://" + location.host + "/_livereload";
var s = new WebSocket(socketUrl);
s.onopen = function(even) {
  console.debug("Live reload: WebSocket connection open");
};
s.onclose = function(even) {
  console.debug("Live reload: WebSocket connection closed");
  var retryIntervalMs = 500;
  function reload() {
    s2 = new WebSocket(socketUrl);
    s2.onerror = function(event) {
      setTimeout(reload, retryIntervalMs);
    };
    s2.onopen = function(event) {
      location.reload();
    };
  };
  reload();
};

s.onerror = function(event) {
  console.debug("Live reload: WebSocket error:", event);
};
```
The interesting part is that I'm not able to reproduce it :sweat_smile: Above, this is the script inserted by the `livereload` middleware. It seems to take the location into account. On my side, in the _404_ page, it does not seem to insert the script at all.

Would it work better if we remove the live reload as you suggested? I'm OK with manually running `Ctrl+R` if needed.

**Comment by gridbugs** [comment] 2024-10-23 08:42
oh weird. Up to you whether to disable live reload. It might just be a me issue. I don't do much work on the site so I can just disable it for myself whenever I need to work on it until we understand the problem better.

**Comment by maiste** [comment] 2024-11-19 09:14
As we don't have to work much on the website anymore I close this issue. We can always reopen if this is needed.

**Closed by maiste** 2024-11-19 09:14 UTC
Labels: bug
